apiVersion: apps/v1
kind: deployment
metadata:
  name: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front-end-pod
  template:
    metadata:
      labels:
        app: front-end-pod
    spec:
      containers:
      - name: frontend
        image: cicd-project-frontend:0.0.0
        ports:
        - containerPort: 3000