apiVersion: apps/v1
kind: Deployment
metadata:
  name: Deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongo-service-pod
  template:
    metadata:
      labels:
        app: mongo-service-pod
    spec:
      containers:
      - name: mongo-service
        image: cicd-project-mongo-service:0.0.0
        ports:
        - containerPort: 27017