apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: microapp-ingress
  namespace: microapp-deploy
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  rules:
  - host: localhost
    http:
      paths:
      - backend:
          serviceName: order-service
          servicePort: 3002