apiVersion: apps/v1
kind: Deployment
metadata:
  name: Deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service-pod
  template:
    metadata:
      labels:
        app: user-service-pod
    spec:
      containers:
      - name: user-service
        image: cicd-project-user-service:0.0.0
        ports:
        - containerPort: 3001